# Generated by Django 2.2.7 on 2019-11-21 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoBoConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=75, verbose_name='Company Name')),
                ('admin_key', models.CharField(max_length=125, verbose_name='WoBo API Key for admin account')),
                ('file', models.FileField(upload_to='wobo_export_files', verbose_name='Latest Export File')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('file_update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
