# Generated by Django 2.2.7 on 2019-11-22 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoBoCompany',
            fields=[
                ('api_key', models.CharField(max_length=75, primary_key=True, serialize=False, verbose_name='API Key')),
                ('company_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='WoBoTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='WoBo Team ID')),
                ('name', models.CharField(max_length=125, verbose_name='Team Name')),
                ('manager', models.IntegerField(null=True, verbose_name='Team Manager')),
                ('sessionDate', models.DateField(null=True, verbose_name='Session Date')),
                ('preMailSent', models.BooleanField(default=False, verbose_name='Pre-session E-Mail sent')),
                ('postMailSent', models.BooleanField(default=False, verbose_name='Post-session E-Mail sent')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing_machine.WoBoCompany', verbose_name='Company')),
                ('parent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing_machine.WoBoTeam', verbose_name='Parent Team')),
            ],
        ),
        migrations.CreateModel(
            name='WoBoTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=125, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('teams', models.ManyToManyField(to='mailing_machine.WoBoTeam', verbose_name='Teams')),
            ],
        ),
        migrations.CreateModel(
            name='WoBoConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=75, verbose_name='Company Name')),
                ('admin_key', models.CharField(max_length=125, verbose_name='WoBo API Key for admin account')),
                ('file', models.FilePathField(verbose_name='Latest Export File')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('file_update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
