# Generated by Django 2.2.7 on 2019-11-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woboconnection',
            name='file',
            field=models.FilePathField(verbose_name='Latest Export File'),
        ),
    ]
