# Generated by Django 2.2.7 on 2019-11-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_machine', '0003_auto_20191123_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woboteam',
            old_name='name',
            new_name='team_name',
        ),
    ]
