# Generated by Django 2.2.7 on 2019-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_machine', '0004_auto_20191125_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='woboteam',
            name='members',
            field=models.ManyToManyField(to='mailing_machine.WoBoTeamMember'),
        ),
    ]
